web_server: yes

schedules:
  - tasks: '*'
    interval:
      minutes: 30

tasks:
  transmission_move_and_rename_movies:
    filesystem:
      path: /transmission_downloads/complete/
      regexp: '.*\.(avi|mkv|mp4)$'
      recursive: yes
    accept_all: yes
    tmdb_lookup:
      language: es
    # imdb_lookup: yes
    # metainfo_movie: yes
    set:
      content_filename: "{{ tmdb_name }} ({{ tmdb_year }})"
    move:
      to: '/plex_downloads/'
      rename: "{{ tmdb_name }} ({{ tmdb_year }})"

  utorrent_move_and_rename_movies:
    filesystem:
      path: /utorrent_downloads/
      regexp: '.*\.(avi|mkv|mp4)$'
      recursive: yes
    accept_all: yes
    tmdb_lookup:
      language: es
    # imdb_lookup: yes
    # metainfo_movie: yes
    set:
      content_filename: "{{ tmdb_name }} ({{ tmdb_year }})"
    move:
      to: '/plex_downloads/'
      rename: "{{ tmdb_name }} ({{ tmdb_year }})"